### ISSUE TITLE
Test on other platforms

### ISSUE THREAD

**Issue by Myoldmopar** [Myoldmopar/ep-transition#57]
I can probably do them, but I can imagine plenty of candidates.

**Comment by mitchute** [comment]
Tried on my Windows 7 machine with PyCharm. I am hitting this error.

```
C:\Python27\python.exe D:/EnergyPlus/Projects/ep-transition/eptransition/transition.py
Traceback (most recent call last):
  File "D:/EnergyPlus/Projects/ep-transition/eptransition/transition.py", line 6, in <module>
    from eptransition.exceptions import ManagerProcessingException
ImportError: No module named eptransition.exceptions
```

**Comment by Myoldmopar** [comment]
Cool man, thanks. You have pip installed?

**Comment by mitchute** [comment]
Aye

**Comment by Myoldmopar** [comment]
Try pip install eptransition.  Then run eptransition /input/file.   I don't
know if the version currently on pypi will do this properly, but the latest
master should stop i can update things.

On Jan 18, 2017 06:39, "Matt Mitchell" <notifications@github.com> wrote:

Aye

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/Myoldmopar/ep-transition/issues/57#issuecomment-273477388>,
or mute the thread

**Comment by mitchute** [comment]
Looks like that is getting closer (I didn't pass any files)

```
C:\Python27\python.exe D:/EnergyPlus/Projects/ep-transition/eptransition/transition.py
usage: transition.py [-h] [-o OUTPUT] [-p PREVIDD] [-n NEWIDD] [-v]
                     original_input
transition.py: error: too few arguments
```

Why can't I run the ```transition``` file before pip installing?

**Comment by mitchute** [comment]
I tried building the docs locally and got this error
```
D:\EnergyPlus\Projects\ep-transition\docs>make html
Running Sphinx v1.4.8
making output directory...

Extension error:
Could not import extension sphinxcontrib.spelling (exception: No module named sphinxcontrib.spelling)
```

**Comment by Myoldmopar** [comment]
The spelling package you are missing is available through pip as shown in the [test descriptions](https://github.com/Myoldmopar/ep-transition/blob/7899ff0ec86e353d32e90360e09b08749173e7b9/tox.ini#L31), let me know if pip installing this works.

**Comment by mitchute** [comment]
Looks like it can't find the IDD. Is it supposed to be brought in with pip?

```
C:\Users\Matt\Desktop>eptransition
usage: eptransition [-h] [-v] input_files [input_files ...]
eptransition: error: too few arguments

C:\Users\Matt\Desktop>eptransition GSHP-GLHE.idf
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\eptransition.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\eptransition\transition.py", line 56, in m
ain
    manager.perform_transition()
  File "C:\Python27\lib\site-packages\eptransition\manager.py", line 139, in per
form_transition
    raise eFAE(self.original_idd_file, eFAE.CANNOT_FIND_FILE, eFAE.ORIGINAL_DICT
_FILE)
eptransition.exceptions.FileAccessException: File access problem occurred:
  Trying to operate on *original dictionary file* at "C:\Python27\lib\site-packa
ges\eptransition\versions\8.5\Energy+.idd"
  Problem: cannot find file
```

**Comment by Myoldmopar** [comment]
Very interesting! Yeah it is supposed to.  I'll check it out.

**Comment by mitchute** [comment]
Looks like it's working now! W00t! :smile:
